### ISSUE TITLE
(URGENT) Crash in IEEE isodoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#106]
Using the https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2 document with metanorma-ieee at Git. This literally worked a few hours ago.

```sh
$ bundle exec metanorma site generate
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[info]: Compiling /Users/me/src/mn/SWF-Corpus_and_IEEEP2874-D2/sources/ieee-p2874/document.adoc ...
[relaton] Edge Mesh: A New Paradigm to Enable Distributed Intelligence in Internet of Things does not have a recognised prefix
[relaton] Digital Twins does not have a recognised prefix
[relaton] Mozilla Web XR does not have a recognised prefix
[relaton] (OGC 20-010) not found.
[relaton] (OGC 21-056r4) not found.
[relaton] Edge Mesh: A New Paradigm to Enable Distributed Intelligence in Internet of Things does not have a recognised prefix
[relaton] Digital Twins does not have a recognised prefix
[relaton] Mozilla Web XR does not have a recognised prefix
AsciiDoc Input: (ID _bibliography): Section not marked up as [bibliography]!
<<...>>

        i.bibdata_i18n(xml.at("//xmlns:bibdata"))
         ^^^^^^^^^^^^^
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/cleanup_boilerplate.rb:102:in `boilerplate_cleanup'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-8e0b73757e30/lib/metanorma/ieee/cleanup_ref.rb:11:in `boilerplate_cleanup'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/cleanup.rb:65:in `cleanup'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/base.rb:163:in `makexml'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/base.rb:114:in `document1'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/base.rb:103:in `document'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.1.4/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/input/asciidoc.rb:18:in `process'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/compile.rb:42:in `process_input'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.10/lib/metanorma/compile.rb:33:in `compile'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/site_generator.rb:89:in `compile'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/site_generator.rb:29:in `block in generate'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/site_generator.rb:29:in `each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/site_generator.rb:29:in `generate'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/site_generator.rb:24:in `generate'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/lib/metanorma/cli.rb:34:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/exe/metanorma:25:in `block in <top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.5.19/exe/metanorma:43:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/metanorma:25:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/metanorma:25:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
	from /Users/me/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by ronaldtse** [comment]
Sorry. Needed to also use Git version of metanorma-standoc. Closing.
