### ISSUE TITLE
Multiple arbitrary dates processing error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#126]
Source ticket: https://github.com/metanorma/mnconvert/issues/161

The source document.adoc contains arbitrary dates `:date_2:` and `:date_3:`:
```
:date_2: epubdate 2013-02-07
:date_3: approved-as-full-use 2012-12-05
```

Full document.adoc:
```adoc
= Software Interface for Maintenance Information Collection and Analysis (SIMICA): Exchanging Test Results and Session Information via the eXtensible Markup Language (XML)
:docnumber: 1636.1
:docstatus: active
:copyright-year: 2013
:published-date: 2013-02-01
:issued-date: 2007-09-27
:date: current-version 2013-02-29
:date_2: epubdate 2013-02-07
:date_3: approved-as-full-use 2012-12-05
:language: en
:doctype: standard
:library-ics: 35.040
:committee: IEEE Standards Coordinating Committee on Test and Diagnosis for Electronic Systems (SCC20)
:semantic-metadata-keywords-IEEE: IEEE standards, Software interfaces, Software maintenance, Software testing, XML
:keywords: Automatic Test Markup Language (ATML), automatic test systems, Extensible Markup Language (XML), IEEE 1636.1, Software Interface for Maintenance Information Collection and Analysis (SIMICA), test results, XML schema
:semantic-metadata-std-id-doi: 10.1109/IEEESTD.2008.6457401
:semantic-metadata-xplore-article-id: 6457401
:stdid-pdf: STD 98107
:stdid-print: STDPD 98107
:isbn-pdf: 978-0-7381-8162-2
:isbn-print: 978-0-7381-8163-9
:semantic-metadata-collab: IEEE Standards Coordinating Committee 20
:semantic-metadata-funding-source-institution: Natural Sciences and Engineering Research Council of Canada
:semantic-metadata-funding-source-institution-id: 10.13039/501100000038
:semantic-metadata-award-group-id: RGPIN312262
:semantic-metadata-funding-statement: This work was supported in part by the Natural Sciences and Engineering Research Council of Canada under Grant RGPIN312262.
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:data-uri-image:
:imagesdir: images
```

`bundle exec metanorma -t ieee -x xml document.adoc` ends with the error:
```
Fatal Error: invalid date
Traceback (most recent call last):
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/exe/metanorma:43:in `<top (required)>'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/exe/metanorma:25:in `block in <top (required)>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli.rb:34:in `start'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `compile'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `each'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `block in compile'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:241:in `compile_document'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:35:in `compile'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:30:in `compile'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:33:in `compile'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:42:in `process_input'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:59:in `process_input_adoc'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/input/asciidoc.rb:18:in `process'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/utils.rb:13:in `convert'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/base.rb:103:in `document'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/base.rb:114:in `document1'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/base.rb:163:in `makexml'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/cleanup.rb:67:in `cleanup'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/metanorma/ieee/cleanup_ref.rb:11:in `boilerplate_cleanup'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-ee3ff38bad1c/lib/metanorma/standoc/cleanup_boilerplate.rb:102:in `boilerplate_cleanup'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/metanorma/ieee/cleanup.rb:119:in `boilerplate_isodoc'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:107:in `bibdata_i18n'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:111:in `bibdata_dates'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:114:in `block in bibdata_dates'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:115:in `block (2 levels) in bibdata_dates'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:129:in `ddMMMyyyy'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-c993ee4b6041/lib/isodoc/ieee/presentation_xml_convert.rb:129:in `parse': invalid date (Date::Error)
```

If I remove `_2` and `_3` just for experiment, then dates (only last one as expected) process successfully.

Expected metanorma xml:
```xml
<date type="current-version"><on>2013-02-29</on></date>
<date type="epubdate"><on>2013-02-07</on></date>
<date type="approved-as-full-use"><on>2012-12-05</on></date>
```

**Comment by Intelligent2013** [comment]
The issue is the source IEEE xml data:
```xml
<pub-date date-type="current-version" iso-8601-date="2013-02-29">
	<day>29</day>
	<month>February</month>
	<year>2013</year>
</pub-date>
```
The 2013 year isn't leap year. Last day in Februry is 28. The date 2013-02-29 doesn't exists.
I don't figure out how one date `:date: current-version 2013-02-29` processed before, but after manual fixing to day `28` this adoc:
```
:date: current-version 2013-02-28
:date_2: epubdate 2013-02-07
:date_3: approved-as-full-use 2012-12-05
```
process ok:
```xml
<date type="current-version">
	<on>2013-02-28</on>
</date>
<date type="epubdate">
	<on>2013-02-07</on>
</date>
<date type="approved-as-full-use">
	<on>2012-12-05</on>
</date>
```
