### ISSUE TITLE
Error: Document type ... is invalid

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#138]
Source: https://github.com/metanorma/mnconvert/issues/173

What are correct values for `span:type`?
(https://www.metanorma.org/author/topics/document-format/bibliography/#annotating-pre-formatted-citations-semantically)

For the bibliography (`span:type[government]`):
```
* [[[B1,1]]], span:title[Code of Federal Regulations Title 40 Part 260 (40CFR260)], U.S. Environmental Protection Agency Hazardous Material Rules. footnote:[CFR publications are available from the U.S. Government Printing Office (http://www.gpo.gsov/).]span:type[government]
```
the error occurs:
```
[relaton-bib] document type "government" is invalid.
Fatal Error: No renderer defined for government
Traceback (most recent call last):
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/exe/metanorma:43:in `<top (required)>'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/exe/metanorma:25:in `block in <top (required)>'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli.rb:34:in `start'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `compile'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `each'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:47:in `block in compile'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/command.rb:241:in `compile_document'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:35:in `compile'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:30:in `compile'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.24/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:33:in `compile'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:42:in `process_input'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.13/lib/metanorma/compile.rb:59:in `process_input_adoc'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.13/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.13/lib/metanorma/input/asciidoc.rb:18:in `process'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/utils.rb:13:in `convert'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/base.rb:116:in `document'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/base.rb:127:in `document1'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/base.rb:176:in `makexml'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup.rb:45:in `cleanup'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:82:in `biblio_cleanup'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:8:in `biblio_reorder'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:9:in `block in biblio_reorder'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:23:in `biblio_reorder1'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.8-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:23:in `block in biblio_reorder1'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-d8801bc8ed9e/lib/metanorma/standoc/cleanup_ref.rb:15:in `biblio_reorder1'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/metanorma/ieee/cleanup_ref.rb:24:in `sort_biblio'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/metanorma/ieee/cleanup_ref.rb:24:in `sort'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/metanorma/ieee/cleanup_ref.rb:25:in `block in sort_biblio'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/metanorma/ieee/cleanup_ref.rb:34:in `sort_biblio_key'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/metanorma/ieee/cleanup_ref.rb:53:in `designator_or_name'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-ieee-46af135a3e71/lib/isodoc/ieee/presentation_ref.rb:63:in `creatornames'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-render-0.4.4/lib/relaton/render/general/render.rb:132:in `parse1'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-render-0.4.4/lib/relaton/render/general/render.rb:124:in `renderer': No renderer defined for government (RuntimeError)
```

I've tried to change to `span:type[report]`, but error occurs again.

**Comment by opoudjis** [comment]
https://www.relaton.org/specs/model/bibtype/

https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc

````
BibItemType |=
    (  "article" | "book" | "booklet" | "manual" |
       "proceedings" | "presentation" | "thesis" | "techreport" |
       "standard" | "unpublished" | "map" | "electronic resource" | 
       "audiovisual" | "film" | "video" | "broadcast" | "software" |
       "graphic_work" | "music" | "patent" | "inbook" | "incollection" |
        "inproceedings" | "journal" | "website" |"webresource"| "dataset" | "archival" | 
        "social_media" | "alert" | "message" | "conversation" | "misc" )
````

I cannot emphasise vehemently enough  how inflexible I am going to be about these values being obeyed in `bibitem/@type`. relaton-render cannot function unless the bibliographic type is well-defined: each type has a defined rendering. 

The type you're looking for in these instances is `techreport`.
