### ISSUE TITLE
PDF: SVG graphic could not be built. Reason: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#163]
Errors occurs in mn2pdf for https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/tree/main/sources/ieee-p2874
```
Rendered page #71.
SVG graphic could not be built. Reason: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.batik.css.engine.CSSEngine.parseStyleSheet(CSSEngine.java:1224)
	at org.apache.batik.css.engine.CSSEngine.parseStyleSheet(CSSEngine.java:1205)
	at org.apache.batik.anim.dom.SVGOMStyleElement.getCSSStyleSheet(SVGOMStyleElement.java:140)
	at org.apache.batik.css.engine.CSSEngine.getStyleSheetNodes(CSSEngine.java:924)
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:786)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:868)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertVisibility(CSSUtilities.java:578)
	at org.apache.batik.bridge.SVGSVGElementBridge.createGraphicsNode(SVGSVGElementBridge.java:141)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:76)
	at org.apache.fop.render.pdf.PDFImageHandlerSVG.handleImage(PDFImageHandlerSVG.java:104)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:249)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:205)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingImageHandler(AbstractIFPainter.java:170)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingDocument(AbstractIFPainter.java:319)
	at org.apache.fop.render.pdf.PDFPainter.drawImage(PDFPainter.java:289)
	at org.apache.fop.render.intermediate.IFParser$Handler$ImageHandler.endElement(IFParser.java:799)
	at org.apache.fop.render.intermediate.IFParser$Handler.endElement(IFParser.java:413)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:534)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:426)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:315)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:346)
...
Rendered page #72.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #73.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #74.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #75.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #76.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #77.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #78.
SVG graphic could not be built. Reason: java.lang.NullPointerException
...
Rendered page #79.
SVG graphic could not be built. Reason: java.lang.NullPointerException
```

PDF:
![image](https://user-images.githubusercontent.com/5559926/199020621-91d9e448-b5b3-44af-ab02-2cbd0ac46c86.png)

**Comment by Intelligent2013** [comment]
HTML renders OK:
![image](https://user-images.githubusercontent.com/5559926/199023134-45ff8f08-683e-4a9b-8840-5bc7caa266c9.png)

**Comment by Intelligent2013** [comment]
After fixing (manually, for testing purposes):
```xml
fill="rgb(255,255,255)" fill-opacity="0.01" stroke="rgb(255,255,255)" stroke-opacity="0.01"
```
new error occurs:
```
SVG graphic could not be built. Reason: org.apache.batik.bridge.BridgeException: null:-1
Cannot find the referenced element:
"#20065"
specified on the element <g> - may be a problem of 'id'
org.apache.batik.bridge.BridgeException: null:-1
Cannot find the referenced element:
"#20065"
specified on the element <g> - may be a problem of 'id'
	at org.apache.batik.bridge.BridgeContext.getReferencedNode(BridgeContext.java:762)
	at org.apache.batik.bridge.BridgeContext.getReferencedElement(BridgeContext.java:804)
	at org.apache.batik.bridge.CSSUtilities.convertMask(CSSUtilities.java:771)
	at org.apache.batik.bridge.AbstractGraphicsNodeBridge.buildGraphicsNode(AbstractGraphicsNodeBridge.java:144)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:224)
```

In SVG there is the anchor `#20065`:
```xml
<mask id="_20065_inject_0" x="948" y="590" width="251" height="29" maskUnits="userSpaceOnUse">
	<rect x="948" y="590" width="251" height="29" fill="white"/>
	<rect x="1017.2306586826348" y="574.1057784431138" width="147.88" height="60.01" fill="black"/>undefinedundefined</mask>
<g mask="url(#20065)">
	<path d="M 1187,602 L 960,607" fill="none" stroke="#97a3b6" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0 0"/>
	<path d="M 960,607 L 967.0977867908091,613.3425469801331 M 960,607 L 966.8118887983203,600.3513422014441 Z" fill="rgb(255,255,255)" stroke="#97a3b6" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
</g>
	
```
but there isn't the element with `id="20065"`, only `_20065_inject_0`.
There are another anchors
```
<g mask="url(#32104)">
<g mask="url(#166ee)"
```

After changing to `<g mask="url(#_20065_inject_0)">`, SVG renders in PDF, but with some missing lines:
![image](https://user-images.githubusercontent.com/5559926/199040478-1c033c56-0abc-4f8e-931a-ec6e8a20d965.png)

**Comment by ronaldtse** [comment]
I've tried opening the file in Adobe Illustrator 2023 and Inkscape:

![](https://user-images.githubusercontent.com/11865/199380616-6c449114-ed52-4f73-8a14-d9bddbe98ab7.png)

![](https://user-images.githubusercontent.com/11865/199380780-79ebf1ab-5b51-4ec8-b104-c4715ffac814.png)

Let's just consider these files invalid.

I believe SVG 1.0 and 1.1 by default only supports CSS 2, not CSS 3. Technically these files are invalid SVG files. SVG 2.0 adopts some CSS 3 properties but is not yet standardized.

**Comment by Intelligent2013** [comment]
No differences between current and latest Batik.

Batik Squiggle 1.9:
![image](https://user-images.githubusercontent.com/5559926/203993537-6b8f7370-7f45-44e2-8002-9f3892c7aec3.png)

Batik Squiggle 1.16 (latest version from Oct, 2022):
![image](https://user-images.githubusercontent.com/5559926/203994272-24551c34-06a1-4202-be7c-e380fb16908c.png)

To do in XSLT on-fly:
- `defs` with `span{ display: inline-block; }` should be removed
- replace `rgba(r, g, b, alpha)` to `<stroke | fill>="rgb(r,g,b)" <stroke | fill>-opacity="alpha">`

**Comment by ronaldtse** [comment]
@Intelligent2013 there's no need to fix this particular SVG issue if it's not a common one. It seems that most graphic editors can't even open it, so I don't think we should worry about it.

**Comment by Intelligent2013** [comment]
@Intelligent2013 there's no need to fix this particular SVG issue if it's not a common one. It seems that most graphic editors can't even open it, so I don't think we should worry about it.

@ronaldtse ok, but I've added a fix into common.xsl already. So let's close it.

> To do in XSLT on-fly:
> - `defs` with `span{ display: inline-block; }` should be removed
> - replace `rgba(r, g, b, alpha)` to `<stroke | fill>="rgb(r,g,b)" <stroke | fill>-opacity="alpha">`

Done.

**Comment by ronaldtse** [comment]
Thank you!
