### ISSUE TITLE
(URGENT) Defensive programming needed in handling bibliographic spans

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#195]
In this branch:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/pull/18

```
[relaton-bib] WARNING: invalid locality type: 
undefined method `text' for nil:NilClass

                           "@type = 'metanorma-ordinal']")).text }
                                                           ^^^^^
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:31:in `block in biblio_ids_titles'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:23:in `each_with_object'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:23:in `biblio_ids_titles'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:6:in `anchor_linkend'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_function/inline.rb:16:in `get_linkend'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_function/inline.rb:215:in `xref1'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_function/inline.rb:197:in `block in xref'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_function/inline.rb:197:in `xref'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_xml_convert.rb:66:in `inline'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_xml_convert.rb:30:in `conversions'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_xml_convert.rb:19:in `convert1'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/convert.rb:229:in `convert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/processor.rb:48:in `output'
```

**Comment by opoudjis** [comment]
IEEE requires the ordinal in a bibliography to be appended to the citation. But there is no ordinal metanorma identifier in this case, because in fact this reference will not be shown to the user: it is an internal cross-reference to another document within a collection. So I will recover from bibliographic entries not having ordinals (and in this case, those cross-references will be suppressed anyway, replaced by links.)
