### ISSUE TITLE
Error: undefined method `children' for nil:NilClass

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#291]
Source ticket: https://github.com/metanorma/metanorma-ogc/issues/579

```
git clone https://github.com/metanorma/mn-samples-ieee
cd mn-samples-ieee
```
update `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "sassc"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "features/displayorder"
gem "metanorma-ieee", git: "https://github.com/metanorma/metanorma-ieee", branch: "features/displayorder"
```

```
cd sources/p987.6
```

`bundle exec metanorma -t ieee -x presentation document.adoc` ends with the error:
```
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:64:in `block in term_related_collapse'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:58:in `each_with_index'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:58:in `term_related_collapse'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:53:in `related_term'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:48:in `block in related'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:48:in `related'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-fe2826e05278/lib/isodoc/presentation_xml_convert.rb:101:in `terms'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/isodoc/ieee/presentation_terms.rb:113:in `terms'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-fe2826e05278/lib/isodoc/presentation_xml_convert.rb:42:in `conversions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-fe2826e05278/lib/isodoc/presentation_xml_convert.rb:24:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-fe2826e05278/lib/isodoc/convert.rb:150:in `convert'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-ieee-cd1021ed7f87/lib/metanorma/ieee/processor.rb:48:in `output'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:170:in `process_output_unthreaded'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:156:in `process_exts1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:130:in `process_ext'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:112:in `block in process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:111:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:111:in `process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:106:in `process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:36:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:45:in `compile_file'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:30:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/command.rb:244:in `compile_document'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/command.rb:48:in `block in compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/command.rb:48:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/command.rb:48:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli.rb:34:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/exe/metanorma:25:in `block in <top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/exe/metanorma:43:in `<top (required)>'
C:/tools/ruby31/bin/metanorma:25:in `load'
C:/tools/ruby31/bin/metanorma:25:in `<main>'
undefined method `children' for nil:NilClass

              .children)}"
              ^^^^^^^^^
```

**Comment by opoudjis** [comment]
This is an unrelated issue caused by https://github.com/metanorma/metanorma-iso/issues/1021 : related/refterm is not being converted to the expected related/preferred
