### ISSUE TITLE
(URGENT) Word generation crash when bibliographic entries are empty (from empty CrossRef data)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#336]
From https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/29

Metanorma Word generation crashes when the following line is inserted into the bibliography:

```adoc
* [[[friston_202312,doi:10.48550/arXiv.2312.07547]]]
```

```
gems/isodoc-2.8.0/lib/isodoc/word_function/postprocess.rb:102:in `block in word_tab_clean'
gems/nokogiri-1.15.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
gems/nokogiri-1.15.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
gems/nokogiri-1.15.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
gems/isodoc-2.8.0/lib/isodoc/word_function/postprocess.rb:101:in `word_tab_clean'
gems/isodoc-2.8.0/lib/isodoc/word_function/postprocess.rb:61:in `word_cleanup'
gems/metanorma-ieee-1.2.1/lib/isodoc/ieee/word_cleanup.rb:25:in `word_cleanup'
gems/metanorma-ieee-1.2.1/lib/isodoc/ieee/word_cleanup.rb:5:in `toWord'
gems/isodoc-2.8.0/lib/isodoc/word_function/postprocess.rb:13:in `postprocess'
gems/isodoc-2.8.0/lib/isodoc/convert.rb:158:in `convert'
gems/isodoc-2.8.0/lib/isodoc/word_convert.rb:20:in `convert'
gems/metanorma-ieee-1.2.1/lib/isodoc/ieee/word_convert.rb:36:in `convert'
gems/metanorma-ieee-1.2.1/lib/metanorma/ieee/processor.rb:43:in `output'
gems/metanorma-1.7.0/lib/metanorma/compile.rb:161:in `process_output_threaded'
gems/metanorma-1.7.0/lib/metanorma/compile.rb:153:in `block in process_exts1'
gems/metanorma-1.7.0/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
gems/metanorma-1.7.0/lib/metanorma/worker_pool.rb:9:in `loop'
gems/metanorma-1.7.0/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
gems/metanorma-1.7.0/lib/metanorma/worker_pool.rb:8:in `catch'
gems/metanorma-1.7.0/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

However, this does not seem to be a Relaton problem:
```sh
$ bundle exec relaton fetch "doi:10.48550/arXiv.2312.07547"
[relaton-doi] (doi:10.48550/arXiv.2312.07547) Fetching from search.crossref.org ...
[relaton-doi] (doi:10.48550/arXiv.2312.07547) Not found.
No matching bibliographic entry found
```

**Comment by opoudjis** [comment]
I have made the Word document not crash in https://github.com/metanorma/isodoc/commit/93dc912db0125ec3bec2ad1c45e2a4d6b528caac , but need to work out why a missing relaton record is causing this behaviour to begin with.

**Comment by opoudjis** [comment]
We are faced with a circumstance where the title is empty, because no metadata is being output by Relaton. In that case, we need to output error text, "[NO INFORMATION AVAILABLE]", to signal in the the output that something has gone wrong; we can't just print a blank.
