### ISSUE TITLE
Insert TM for cover-page instance of IEEE identifiers

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#71]
Source issue: https://github.com/metanorma/metanorma-ieee/issues/66

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/176664794-21830d07-f91c-498c-a523-c0229cd5e412.png)

### 1. how to set multiple values in `:merges:`?
This:
```
:merges: IEEE 802.1Xbx-2014;IEEE 802.1Xck-2018
```
raises the error:
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
[relaton-ieee] ("IEEE 802.1Xck-2018") fetching...
Fatal Error: undefined method `[]' for nil:NilClass
Traceback (most recent call last):
        58: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        57: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        56: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/exe/metanorma:43:in `<top (required)>'
        55: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/exe/metanorma:25:in `block in <top (required)>'
        54: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/lib/metanorma/cli.rb:34:in `start'
        53: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        52: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        51: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        50: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        49: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/lib/metanorma/cli/command.rb:47:in `compile'
```

### 2. how to put `™` sign?
```
:merges: IEEE 802.1Xbx(TM)-2014
```
raises the error:
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
[relaton-ieee] ("IEEE 802.1Xbx(TM)-2014") fetching...
Fatal Error: undefined method `[]' for nil:NilClass
Traceback (most recent call last):
        58: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        57: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        56: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/exe/metanorma:43:in `<top (required)>'
        55: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/exe/metanorma:25:in `block in <top (required)>'
        54: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.18/lib/metanorma/cli.rb:34:in `start'
        53: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        52: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        51: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
```

**Comment by opoudjis** [comment]
Do not put the ™ sign in. *I* do that.

Merges: I will need to investigate.

**Comment by ronaldtse** [comment]
@opoudjis another reason why relaton/relaton-ieee#21 is not a Metanorma issue?

**Comment by opoudjis** [comment]
> Presentation of the document identifier seems to be a bibliographic thing. 

Nonsense. 

> The rule is that the ®/™ is inserted after first mention only

In what planet is "first mention" not a document presentation thing?

And as I have already said in that ticket, I have conceded to you allowing the two versions of the identifier, trademarked or not, to be given by relaton.

**Comment by opoudjis** [comment]
@Intelligent2013 The crash is a relaton-ieee issue. https://github.com/relaton/relaton-ieee/issues/23

**Comment by opoudjis** [comment]
Thanks to update to relaton-ieee, you can get the ™- or ®-version of the target identifier from bibitem, as `bibitem/docidentifier[scope='trademark']`:

````
<relation type="merges">
<bibitem>
  <fetched>2022-07-25</fetched>

<title type="main" format="text/plain" language="en" script="Latn">Standard for Local and Metropolitan Area Networks: Media Access Control (MAC) Bridges</title>

  <uri type="src">https://standards.ieee.org/ieee/802.1D/1028/</uri>
  <docidentifier type="IEEE" primary="true">IEEE 802.1D-1990</docidentifier>
  <docidentifier type="IEEE" scope="trademark" primary="true">IEEE 802.1D®-1990</docidentifier>
...
````

I'm going to generate the "revision of... incorporating..." text as `/bibdata/title[@type = 'provenance']`

**Comment by opoudjis** [comment]
````
<title type="provenance" language="en" format="application/xml">Revision of ABC<br/>Incorporates IEEE 802.1D®-1990 and IEEE 802.1Xck-2018</title>
````
